language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_deploy:
  - npm install netlify-cli -g
  - npm run build
script:
  - npm run build
notifications:
  slack: hackclub:KqNigPX4nP2Iq54hF93LjqRR
    on_success: always
deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
  skip_cleanup: true
on:
  branch: main