language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_deploy:
  - npm install netlify-cli -g
  - npm run build
script:
  - npm test
  - npm run build
notifications:
  slack:
    on_success: always
deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
  skip_cleanup: true
on:
  branch: main